language: python
python:
  - "2.7"
  env: BOTO_CONFIG=/dev/null
  - "3.6"
  env: BOTO_CONFIG=/dev/null
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m unittest discover -s tests/ # or py.test for Python versions 3.5 and below

sudo: false
